### ISSUE TITLE
support for custom ExecutorProvider in SpannerOptions.Builder

### ISSUE THREAD

**Issue by pravsingh** [googleapis/java-spanner#1262]
**Is your feature request related to a problem? Please describe.**
I would like to configure ExecutorProvider in SpannerOptions so can control the executor configs. Currently the Builder doesn't provide any setter for it. Due to this, the asyncExecutorProvider is null and hence the below code always falls back to the default provider:

```java
SpannerImpl(SpannerRpc gapicRpc, SpannerOptions options) {
...

    this.asyncExecutorProvider =
        MoreObjects.firstNonNull(
            options.getAsyncExecutorProvider(),
            SpannerOptions.createDefaultAsyncExecutorProvider());
...
}
```

**Describe the solution you'd like**
Add setter in SpannerOptions.Builder class.

**Describe alternatives you've considered**
So far found no alternative.

**Additional context**
Discussed about this issue at [discussion](https://github.com/googleapis/java-spanner/pull/81#discussion_r659277576)

**Comment by thiagotnunes** [comment]
@olavloite Could you take a look at this? I think you were already following this issue before.
