### ISSUE TITLE
There should be a type error when trying to set integers as strings for INT64

### ISSUE THREAD

**Issue by skuruppu** [googleapis/java-spanner#138]
A customer reported that they expected the following type conversion in the [Mutation API](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/spanner/Mutation.html) to produce an error but it doesn't.

```
Mutation mutation =
    Mutation.newInsertOrUpdateBuilder("table")
        .set("int64_column")
        .to("123")
        .build();
```

A `FLOAT64` conversion produces an error.

**Comment by olavloite** [comment]
I'm afraid there's not much we can do about that in the client library. Mutations are sent as a protobuf `ListValue` to Cloud Spanner in a `Commit` request. A `ListValue` is a repeated field of `Value` which can contain the following values:


Field name | Type | Description
-- | -- | --
null_value | NullValue | Represents a null value.
number_value | double | Represents a double value.
string_value | string | Represents a string value.
bool_value | bool | Represents a boolean value.
struct_value | Struct | Represents a structured value.
list_value | ListValue | Represents a repeated Value.

`INT64` Spanner values are encoded as `string`. The same also applies to `DATE` and `TIMESTAMP` Spanner values. The client library does not keep a copy of the schema information in memory that could be used to check this before sending it, so as long as the value that is set is a valid `INT64`/`DATE`/`TIMESTAMP` value, the backend will accept it.

The only way to fix this would be to try to keep a copy of the `INFORMATION_SCHEMA`  in memory in the client library and check these values against that. The biggest challenge with that would be to keep it in sync with the backend.
