### ISSUE TITLE
Spanner emulator for local testing

### ISSUE THREAD

**Issue by sartorimatt** [googleapis/java-spanner#139]
Our team is using Cloud Spanner throughout our infrastructure. We are currently testing our code using a remote Spanner instance but are interested in an emulator that can be run locally so as to cut down on test time and allow our testing to scale. Is there any plan to support a local Spanner emulator? Thanks!

**Comment by olavloite** [comment]
@sartorimatt 
A beta version of an official emulator for Cloud Spanner has now been released. More information can be found here: https://cloud.google.com/spanner/docs/emulator

**Comment by sartorimatt** [comment]
Excellent! Thank you for the pointer @olavloite
