### ISSUE TITLE
How to get appropriate data type value from mutation in Google Spanner?

### ISSUE THREAD

**Issue by nitinsridar** [googleapis/java-spanner#15]
In the code below I can get the appropriate data type value.

Map<String, Value> mutationMap = mutation.asMap();
Value locationValue = mutationMap.getOrDefault("location", null);
Long location = locationValue .getInt64();

How to get it within a loop?

new Gson().toJson(mutation.asMap().entrySet().stream().collect(Collectors.toMap(Entry::getKey,e->e.getValue().toString())));

In the above I'm converting everything to string. If the value has data type INT64, how do I get that?

**Comment by olavloite** [comment]
There's no standard method in the Java client library that does this, as `Mutation` objects are primarily intended for sending mutations to the backend, and not for reading out or sending to other services. The best way to do what you want, would be to add a method like this to your own code, and use that to read the actual underlying value from a mutation:

```java
  Object getUnderlyingValue(Value v) {
    switch(v.getType().getCode()) {
      case ARRAY:
        switch(v.getType().getArrayElementType().getCode()) {
          case BOOL:
            return v.getBoolArray();
          case BYTES:
            return v.getBytesArray();
          case DATE:
            return v.getDateArray();
          case FLOAT64:
            return v.getFloat64Array();
          case INT64:
            return v.getInt64Array();
          case STRING:
            return v.getStringArray();
          case TIMESTAMP:
            return v.getTimestampArray();
          case STRUCT:
            // Array of struct is not supported.
          case ARRAY:
            // Array of array is not supported.
          default:
            break;
        }
        break;
      case BOOL:
        return v.getBool();
      case BYTES:
        return v.getBytes();
      case DATE:
        return v.getDate();
      case FLOAT64:
        return v.getFloat64();
      case INT64:
        return v.getInt64();
      case STRING:
        return v.getString();
      case STRUCT:
        return v.getStruct();
      case TIMESTAMP:
        return v.getTimestamp();
      default:
        break;
    }
    throw new IllegalStateException("Value with unknown type: " + v.toString());
  }
```

**Comment by olavloite** [comment]
@nitinsridar Could you indicate whether the above example solves this for you? I don't think this is a very common use case, so it's not something that I think we want to add to the client library. If you add the above code snippet to your own code base, you should however be able to achieve what you wanted.

**Comment by olavloite** [comment]
Closing this as we have not heard back in a while. Please re-open if additional information is needed.
