### ISSUE TITLE
Provision more channels with fewer sessions in each when using gRPC-GCP channel pool

### ISSUE THREAD

**Issue by skuruppu** [googleapis/java-spanner#1566]
#1227 introduced an option to use the gRPC-GCP channel pool. When using this pool, to make sure there are sufficient channels available to move the sessions to a different channel if a network connection in a particular channel fails, it's recommended that each channel try to only support ~50 concurrent requests.

Currently, we have 4 channels by default, with max sessions = 400 so that each channel likely has at most 100 sessions.

So this request is to double the number of channels initialized (to 8) if the gRPC-GCP channel pool is being used.

**Comment by ansh0l** [comment]
cc @harshachinta
