### ISSUE TITLE
ITInstanceAdminTest #update / #updateViaEntity fail when two tests are running simultaneously

### ISSUE THREAD

**Issue by thiagotnunes** [googleapis/java-spanner#1626]
The update and updateViaEntity tests update the current instance display name to a random one. If there are two tests running simultaneously the assertions might fail, because the updated name can match the wrong display name.

We need to fix these tests so that they are self-contained.

**Comment by ansh0l** [comment]
cc @rajatbhatta  to take a look at the related issue

**Comment by mpeddada1** [comment]
thanks for looking into this @rajatbhatta! Any update on this?
