### ISSUE TITLE
[Question] Best Spanner client usage patterns?

### ISSUE THREAD

**Issue by dzou** [googleapis/java-spanner#1725]
Hey, we wanted to ask if we could get some guidance about some best practices for writing application code using the Spanner client.

1. In general, are Spanner JOINs performant or should they be used sparingly in practice? We're considering putting all of our data (which has a simple parent-child relationship) onto Spanner and then frequently running JOIN queries. Alternatively, we could separate our data and query from Spanner and other data sources, and then merge ResultSets on the application-side (basically avoiding a JOIN on Spanner but merging results on the application-side). Curious which approach you think would be better.

2. If we interleave tables (which co-locates rows of child tables with parent tables), does the overall query performance to either table degrade? I am curious if queries which do not need the interleaved relationship would slow down due to how the rows are co-located differently.

**Comment by ansh0l** [comment]
@dzou I'm not sure if I can make generalised recommendations here that will be really helpful. Answers would depend on your specific use case (patterns for data access, size/structure of data, etc), so if you are in touch with your account team, they would be able to help you best.

That said, for
1. Please go through Writing [Efficient Queries for Joins](https://cloud.google.com/spanner/docs/sql-best-practices#write_efficient_queries_for_joins) and [Join Types](https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#join_types) for understanding joins in Spanner better
2. Make sure that you are following [Schema Design Best practices](https://cloud.google.com/spanner/docs/schema-design) to avoid hotspots and have appropriate [Parent Child Table relationships](https://cloud.google.com/spanner/docs/schema-and-data-model#parent-child_table_relationships)

**Comment by dzou** [comment]
Thanks, this helps. 👍
