### ISSUE TITLE
Support for bool Array in AbstractResultSet

### ISSUE THREAD

**Issue by MedhaCS1010** [googleapis/java-spanner#2183]
[Request/Enhancement]
[Abstract Result Set](https://github.com/googleapis/java-spanner/blob/028505b26f8da0541e8e281fc5f6646b469b332d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L1296) provides option to get array result as unmodifiable list for all the supported types but for primitive types like `int64` and `float64` it also provides an option to get the result as [array](https://github.com/googleapis/java-spanner/blob/028505b26f8da0541e8e281fc5f6646b469b332d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L1419).  
Can we extend this functionality to support for `boolean` as well because `bool` is also a primitive? 

[Solution]
We can add another BoolArray class similar to [Int64Array](https://github.com/googleapis/java-spanner/blob/028505b26f8da0541e8e281fc5f6646b469b332d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L1296)

Will be happy to raise the PR for the same.

**Comment by gauravpurohit06** [comment]
In my opinion adding the primitive support for boolean like we have for  `int64` and `float64` will definitely going to be a performance gain as primitives are a bit faster and we don't have to construct new wrapper objects for each array element.  

- Your implementation for bool will be similar to [Int64Array](https://github.com/googleapis/java-spanner/blob/028505b26f8da0541e8e281fc5f6646b469b332d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L1296) implementation. 
-  You don't have to do any parsing from String like we are doing for `Int64` & `Float64 `as the wire type for `boolean` is the primitive boolean, wee can just use `proto.getBoolValue()`.

**Comment by gauravpurohit06** [comment]
@olavloite, can you please chime in and provide your thoughts here?

**Comment by gauravpurohit06** [comment]
Closing it here as we already have `boolean[] getBooleanArray(..)` support.  @MedhaCS1010 , please feel free to log new issues and enhancements request. Thank you!!
