### ISSUE TITLE
Switch to GitHub actions for unit tests

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-spanner#219]
It looks like the Spanner units need a few environment variables set which we are not providing currently (GOOGLE_CLOUD_PROJECT and maybe others?) See #218 

We can look into globally adding some environment variables for the unit tests, or look into mechanisms for selectively added environment variables.

Note: integration & sample tests are unaffected

**Comment by hengfengli** [comment]
@olavloite Has this issue been resolved?

**Comment by olavloite** [comment]
@hengfengli Yes, this was fixed in #235
