### ISSUE TITLE
Retry on "UNKNOWN: channel closed"  errors

### ISSUE THREAD

**Issue by yuanyuan-gl** [googleapis/java-spanner#2307]
The request can be failed due to occasional networking issue, which returns an "UNKNOWN: channel closed"  error.

The client library should retry on such cases.

**Comment by arpan14** [comment]
@yuanyuan-gl Just to gauge the right priority of this issue can you help us with two queries,
1. Where are you using the client? Can you specify few details about your application.
2. What is the impact on your application in the absence of retries?

**Comment by arpan14** [comment]
@yuanyuan-gl I read on this behaviour and learnt that client libraries use gRPC under the hood. When a channel is closed, gRPC recreates a new channel and the request gets retried. So I think we don't need to add any new handlings on client libraries. If you still think this issue persists, then I would request you to provide more details (preferably the stack-trace).
