### ISSUE TITLE
Hanging indefinitely

### ISSUE THREAD

**Issue by Sourc** [googleapis/java-spanner#2494]
Hi, this issue is related to the support case 45040288.

A short while ago we had multiple of our services that use Spanner, both with the latest Spanner version at the time (6.42.1) but some using slightly older ones as well, hang indefinitely on [this particular row](https://github.com/googleapis/java-spanner/blob/977b5851b9cc1a538dedf57d006483dc58ec90b9/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L990). The only solution when that happened was to restart the service, which would fix the issue - even though it often happened again after a while.

This happened quite often during a two week period towards at least one particular Spanner instance, and we haven't seen it since a couple of weeks now. We have also not been able to determine the exact conditions under which this issue presents itself - We do not believe it to be a recent code change, as we saw it on some services that haven't been updated for months. The code that froze was just a regular `resultSet.next()` call, preceeded by a `singleUse().read(...)`, with appropriate closing etc.

Since we don't have a reliable way to reproduce this issue, I believe the most straightforward way to solve it would be to implement a timeout mechanic like mentioned in the TODO-comment in the code already.

**Comment by rajatbhatta** [comment]
Hi @Sourc, thanks for logging the issue!

Do you mean v6.42.1 (and not 6.24.1 in your initial description)? Support case mentions v6.42.1.

**Comment by Sourc** [comment]
Hi, yes a typo. I've corrected it now👍
