### ISSUE TITLE
Literal Struct Fields Aren't Accessible By Name

### ISSUE THREAD

**Issue by senbrow** [googleapis/java-spanner#2611]
#### Environment details

OS type and version: `Linux Mint 5.15.0-79-generic #86-Ubuntu`
Java version: `20`
Spanner Java Library Version: `6.42.3`

#### Steps to reproduce

1. Read an `ARRAY` of `STRUCT`s in a query into a `ResultSet`
2. Attempt to extract a `STRUCT` field via its name
3. Observe that an exception is thrown.

**NOTE: this does *not* happen when accessing the field by ordinal index.**

#### Code example

These are JUnit4 testcases implemented with AssertJ assertions:

EXAMPLE (**not** working as expected):

```java
    DatabaseClient client = <...>;
    var resultSet =
        client.singleUse().executeQuery(Statement.of(
            """
            SELECT ARRAY<STRUCT<INT64, STRING>>[
                STRUCT(1 AS x, "foo" AS y)
            ]
            AS StructList"""));

    assertThat(resultSet.next()).isTrue();
    assertThat(resultSet.getStructList("StructList"))
        .element(0)
        .extracting(s -> s.getLong("x"))
        .isEqualTo(1L);
```
Result:
```
java.lang.IllegalArgumentException: Field not found: x
        at com.google.cloud.spanner.Type.getFieldIndex(Type.java:395)
        at com.google.cloud.spanner.AbstractStructReader.getColumnIndex(AbstractStructReader.java:459)
        at com.google.cloud.spanner.AbstractStructReader.getLong(AbstractStructReader.java:138)
```

EXAMPLE 2 (working as expected):

```java
    DatabaseClient client = <...>;
    var resultSet =
        client.singleUse().executeQuery(Statement.of(
            """
            SELECT ARRAY<STRUCT<INT64, STRING>>[
                STRUCT(1 AS x, "foo" AS y)
            ]
            AS StructList"""));

    assertThat(resultSet.next()).isTrue();
    assertThat(resultSet.getStructList("StructList"))
        .element(0)
        .extracting(s -> s.getLong(0))
        .isEqualTo(1L);
```
Result:
```
Testcase passes successfully.
```

**Comment by senbrow** [comment]
Note: the examples above connect to an emulated spanner instance running in a local Docker container to evaluate the SQL.

**Comment by arpan14** [comment]
@senbrow I'll look into reproducing this issue at our end and get back.

**Comment by arpan14** [comment]
I don't think this is a valid query. When I try to execute this against a Spanner table from the cloud console, I get the below error

```
Statement failed: Unsupported query shape: This query returns a STRUCT value constructed by a scalar subquery or struct construction syntax. Spanner does not yet support returning STRUCT except as arrays-of-structs. Rephrase your query to produce the struct value with an array subquery: ARRAY(SELECT AS STRUCT expr ...) or flatten the structs fields into the result.
```

Could you send a valid select statement against a Spanner table?

**Comment by sean-cinnamon** [comment]
It doesn't seem correct for the emulator to allow a query shape that the cloud Spanner doesn't support.
This bit us during development because we assumed that the emulator was sufficient for determining viability.

How/where should I file a bug for the emulator to fail queries with arrays-of-structs?

**Comment by arpan14** [comment]
@sean-cinnamon Valid feedback. I'll loop in the right folks internally to investigate this. Meanwhile, could you raise a issue at the emulator repository - https://github.com/GoogleCloudPlatform/cloud-spanner-emulator .
