### ISSUE TITLE
Run samples test on both Java 8 and Java 11

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#283]
The Spanner sample tests should be executed on both Java 8 and Java 11, as some dependencies are only included in Java 9 and higher. This has caused broken builds in Java 9 and higher to pass without notice.

See also #280

**Comment by olavloite** [comment]
@chingor13 Is this something you could help with? I do not know how to add an additional Kokoro build to execute the Samples test on both Java 8 and Java 11.

**Comment by skuruppu** [comment]
I can help out with this. I'm trying to understand the Kokoro configs and will get back to you once I learn how this is setup.

**Comment by thiagotnunes** [comment]
@skuruppu @olavloite the sample test badges are not shown in the README file as well, should we add them or is that going to be confusing?

**Comment by olavloite** [comment]
@thiagotnunes Those test badges are automatically generated for all Java clients for the different Google Cloud projects here: https://github.com/googleapis/synthtool/tree/master/synthtool/gcp/templates/java_library

So if we were to change that, we would have to change it for all Java clients.

I don't feel very strongly either way about this.

**Comment by thiagotnunes** [comment]
Got it, thanks @olavloite. I will refrain from changing the badges now due to the impact of the change. I will follow up on this decision with @skuruppu.

**Comment by olavloite** [comment]
@thiagotnunes Can this issue be closed now that #345 has been merged?

**Comment by thiagotnunes** [comment]
@olavloite not yet, I still need to do something in the backend to enable the tests. Hopefully today it will get sorted out and I will close #345.

**Comment by thiagotnunes** [comment]
We should now see the samples tests for java8 and java11 being run in kokoro
