### ISSUE TITLE
Rust SDK for Google Cloud Spanner?

### ISSUE THREAD

**Issue by dotjon0** [googleapis/java-spanner#3417]
Hi, are you planning to make a Rust SDK for Google Cloud Spanner? Was not sure where to ask this question.

**Comment by jmakeig** [comment]
[Spanner PostgreSQL interface](https://cloud.google.com/spanner/docs/postgresql-interface) databases allow you to connect clients via the [PostgreSQL wire protocol](https://cloud.google.com/spanner/docs/pgadapter), in addition to supporting a broad subset of PostgreSQL schemas and queries. We’ve had at least one customer who has successfully hooked up the [PostgreSQL Rust driver](https://github.com/sfackler/rust-postgres) this way. 

In general, low-level drivers that provide a thin wrapper around the query interface should work out-of-the-box with Spanner. Higher-level tools and ORMs that build PostgreSQL syntax queries and access PostgreSQL-specific metadata may not work as well today with Spanner. We’re working to expand this coverage.

**Comment by rahul2393** [comment]
@dotjon0 we will share here once we have plans for it.

Closing this for the time being.
