### ISSUE TITLE
feat: add transaction keep-alive to Connection API

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#346]
See https://github.com/spring-cloud/spring-cloud-gcp/issues/2453 for detailed discussion.

Read/write transactions in Cloud Spanner are automatically aborted by Cloud Spanner if they are idle for more than 10 seconds. For connection based APIs this can pose a challenge, especially during debugging, as stepping through the code will in most cases cause the active read/write transaction to be aborted because of the long delays between each step.

**Comment by thiagotnunes** [comment]
Will not implement this at the moment

**Comment by olavloite** [comment]
Some additional information specifically for the Connection API: The Connection API contains an internal retry feature that will automatically retry aborted transactions. If a read/write transaction is idle for more than 10 seconds, it will automatically be aborted by the backend. In such a scenario where a transaction has been idle for more than 10 seconds, the Connection API will automatically restart the transaction and replay all statements up until the idleness when a new statement is executed on the transaction. This replay will succeed as long as no other transactions have made changes that would make the (possible) outcome of the idle transaction be different than the initial attempt. This approach is a lot more efficient than artificially holding on to locks on the backend by keeping a transaction alive by pinging it every X seconds.
