### ISSUE TITLE
Using Guava classes in AsyncResultSet exposes it on API surface

### ISSUE THREAD

**Issue by nielm** [googleapis/java-spanner#410]
The AsyncResultSet interface has two members that return a Future<ImmutableList<>>. and have a Guava Function as a parameter

https://github.com/googleapis/java-spanner/blob/77398f2771d5531b8f703c17df694dc77e42f35f/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSet.java#L206-L207

This exposes these two Guava classes in the API surface of the spanner client library, which it did not before.

Good java practice is to refer to objects by their interfaces (Effective Java (Blosch), item 64)
_"If appropriate interface types exist, then parameters, return values,
variables, and fields should all be declared using interface types."_

So these functions should return Future<List<>> and take a java.util.function.Function

But java.util.function.Function does not appear until JDK8, so Guava Function still needs to be used.

**Comment by nielm** [comment]
Example pull request in #411

**Comment by nielm** [comment]
This may not even be possible to be fixed complely -- java.util.function.Function is only since JDK 1.8, so if we want to keep JDK 1.7 compatibility, then we would have to keep com.google.common.base.Function...

**Comment by thiagotnunes** [comment]
@nielm as you mentioned, we do need to maintain compatibility with the `JDK 1.7`, so we can not change the types here. Other than that, this would be a breaking change in the interfaces, so we would need to add new methods, deprecate the old ones and eventually remove them.

I do agree that we should this change eventually, if we stop supporting the version `1.7`. As you pointed out, we should program to interfaces, not implementations. However, I don't think we should go for this change at the moment, since we would only be able to change the `ImmutableList` to `List`.

**Comment by nielm** [comment]
I forgot to mention an example knock-on effect -- Beam tries to restrict the classes exposed by its API, and exposing ImmutableList also exposes:
```
            com.google.common.collect.ImmutableCollection.class
            com.google.common.collect.ImmutableCollection.Builder.class
            com.google.common.collect.ImmutableList.class
            com.google.common.collect.ImmutableList.Builder.class
            com.google.common.collect.UnmodifiableIterator.class
            com.google.common.collect.UnmodifiableListIterator.class
```
(see [BEAM PR#12695](https://github.com/apache/beam/pull/12695#pullrequestreview-478983096) )

Perhaps just changing the ImmutableList to List - which is possible while keeping 1.7 compatibility?

**Comment by nielm** [comment]
> Perhaps just changing the ImmutableList to List - which is possible while keeping 1.7 compatibility?

I would also suggest that it is better to make this change sooner rather than later -- the async API is a new feature, and not many customers would be using it yet, so the impact of a breaking change at this point would be minor

I have updated my suggested PR #411 to only include the List changes.

**Comment by olavloite** [comment]
> I would also suggest that it is better to make this change sooner rather than later -- the async API is a new feature, and not many customers would be using it yet, so the impact of a breaking change at this point would be minor

I agree with that. I think that we can make this change now without causing very much pain for most of our users, and this change is possible to implement without breaking JDK7 compatibility.

**Comment by thiagotnunes** [comment]
> I would also suggest that it is better to make this change sooner rather than later -- the async API is a new feature, and not many customers would be using it yet, so the impact of a breaking change at this point would be minor

That is a good point, let's push this out then. I just need to make sure that we are following the correct protocol for breaking changes if we are changing the APIs or if we need to deprecate / create new methods with the changes made.

**Comment by nielm** [comment]
> That is a good point, let's push this out then. I just need to make sure that we are following the correct protocol for breaking changes if we are changing the APIs or if we need to deprecate / create new methods with the changes made.

The point here is that it _has_ to be a breaking change in order to remove the guava ImmutableList form the public API surface...
Deprecating and adding new methods will not fix the issue, as the old methods will still be public.

**Comment by thiagotnunes** [comment]
@nielm no worries, if you could amend your commit to mark it as a breaking change that would work.

Just to be clear, if we would have done the deprecation, that would have given time for clients to migrate to the new API and then we would remove the old methods. But it seems we don't need such notice and we can introduce a breaking change.
