### ISSUE TITLE
Spanner: com.google.cloud.spanner.ValueBinder.to() in Scala for gives java.lang.NoSuchFieldError: NUMERIC , for versions >= 1.59.0

### ISSUE THREAD

**Issue by viktorjonsson** [googleapis/java-spanner#630]
com.google.cloud.spanner.ValueBinder.to() in Scala for gives java.lang.NoSuchFieldError: NUMERIC , for versions >= 1.59.0.
Downgrading to 1.58.0 fixes the problem.

#### Environment details

OS type and version: MacOS version 10.15.7
Java version: openjdk 11.0.8 2020-07-14 LTS
Scala version: 2.12.10
spanner version(s): com.google.cloud.google-cloud-spanner 1.59.0

#### Steps to reproduce

  1. Import com.google.cloud.google-cloud-spanner 1.59.0
  2. Call ValueBinder.to("test")

#### Code example

```scala
val resultBuilder: Struct.Builder = Struct.newBuilder()
resultBuilder.set("test_key").to("test_value")
```

#### Stack trace
```
[error] java.lang.NoSuchFieldError: NUMERIC
[error] 	at com.google.cloud.spanner.Type$Code.<clinit>(Type.java:182)
[error] 	at com.google.cloud.spanner.Type.<clinit>(Type.java:44)
[error] 	at com.google.cloud.spanner.Value$StringImpl.<init>(Value.java:1013)
[error] 	at com.google.cloud.spanner.Value$StringImpl.<init>(Value.java:1010)
[error] 	at com.google.cloud.spanner.Value.string(Value.java:140)
[error] 	at com.google.cloud.spanner.ValueBinder.to(ValueBinder.java:95)

```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by olavloite** [comment]
@viktorjonsson Would you mind sharing your entire dependency tree?

At first hand it seems that your code is failing [here](https://github.com/googleapis/java-spanner/blob/0f991960df4d523ce082ab11accad727282041df/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java#L182), which again seems to indicate that your environment is using version 1.59.0 of the hand written client library (`google-cloud-spanner`), but a pre-1.59.0-version of the generated proto files code (`proto-google-cloud-spanner-v1`). The `NUMERIC` [type code was added to that code base](https://github.com/googleapis/java-spanner/blob/0f991960df4d523ce082ab11accad727282041df/proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeCode.java#L163) as well in 1.59.0.

**Comment by viktorjonsson** [comment]
Hi @olavloite !

You are correct. I found some funkiness in my dependencies and when I was able to resolve them, it worked! Sorry I cannot share more of the dependency tree.

Thank you very much for the help! I will close this issue now.
