### ISSUE TITLE
Deprecate `maxIdleSessions`

### ISSUE THREAD

**Issue by skuruppu** [googleapis/java-spanner#865]
From a quick search of the repo, it seems that we're no longer using this [field](https://github.com/googleapis/java-spanner/blob/e1e915289755e5f46ba07569d85afda5df5e3f0d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java#L56). We should mark it as deprecated since otherwise users try to set the field.

**Comment by olavloite** [comment]
It is actually still being used, however the usefulness of it might be up for discussion: https://github.com/googleapis/java-spanner/blob/54cfa0f70f9b117ff50310adc5e01282e4bd82ed/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L1684

The basic usage of it in the session pool is as follows:
1. Always create `MinSessions` sessions, and never go below this value, regardless of how many sessions are actually used.
2. If more sessions than `MinSessions` are needed, the pool will create additional sessions, as long as this does not exceed `MaxSessions`.
3. When keeping sessions alive (the ping query) the session pool will try to keep `MinSessions + MaxIdleSessions` alive.

So setting a value for `MaxIdleSessions` will prevent additional sessions above `MinSessions` from expiring.

**Comment by thiagotnunes** [comment]
I think this is still useful if we want to keep min and max sessions configurable (if we don't want to have just a single num sessions). I would keep this configuration, but would like to know if you agree @skuruppu .

**Comment by skuruppu** [comment]
It seems that the intention is to keep X number of sessions alive in the pool. In that case, couldn't the user increase `MinSessions` to X so that they don't need to configure three different parameters?

This is just my opinion but I think we should minimize the number of configurable parameters, especially if the parameters don't directly help to optimize the performance of the client.

**Comment by thiagotnunes** [comment]
Yes, I think you are right, the only difference I can see is if the user does not want all the maxIdleSessions created before they are necessary, but that would be a very niche case.

**Comment by olavloite** [comment]
> It seems that the intention is to keep X number of sessions alive in the pool. In that case, couldn't the user increase `MinSessions` to X so that they don't need to configure three different parameters?

> Yes, I think you are right, the only difference I can see is if the user does not want all the maxIdleSessions created before they are necessary, but that would be a very niche case.

Correct, this setting will prevent the excess sessions from being removed from the session pool, but they will only be created if the application actually needs more than `MinSessions` sessions. So setting `MinSessions` to a higher value would achieve almost the same. I think `MaxIdleSessions` made sense before `BatchCreateSessions` was introduced, as setting a (very) high value for `MinSessions` would cause a large burst of `CreateSession` RPCs when a session pool was created. That is no longer the case, and I think that this setting does not really add any value any more. Users should instead increase the value of `MinSessions` if they are currently using `MaxIdleSessions` in combination with a lower value for `MinSessions`.
