### ISSUE TITLE
Thread.sleep is one 1000 times too fast

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#874]
The example usage for `TransactionManager` contains an error in the retry part: The returned timeout is already in milliseconds, but the example [divides it by 1000](https://github.com/googleapis/java-spanner/blob/5af36739532037360dfd504a4a0988562550526c/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java#L335) before passing it to `Thread.sleep`.

**Comment by elharo** [comment]
Moved this to P1 since it's not just in the docs or the tests.

**Comment by olavloite** [comment]
> Moved this to P1 since it's not just in the docs or the tests.

For clarity and the release notes:
The [call that used the wrong value](https://github.com/googleapis/java-spanner/blob/953ab2231a1b7c1f9fae4025c38f3519c58b513f/google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java#L731) that is not in documentation or tests, is only for the JDBC driver. So the actual bug (other wrong documentation) does not affect the client library, but the JDBC driver.
