### ISSUE TITLE
Unable to read timestamp from ReadOnlyTransaction.getReadTimestamp()

### ISSUE THREAD

**Issue by LCvijovic09** [googleapis/java-spanner#958]
Hi,
I was trying to use ReadOnlyTransaction.getReadTimestamp() function but I keep running into exception:
"Method can only be called after read has returned data or finished"
I have returned one or two records from DB, but I can't read timestamp.
Below is sample code how and what I am doing.

```
IO {
      val db    = spannerClientInstance
      val rotxn = db.singleUseReadOnlyTransaction()

      val sql = "SELECT " +
        "Name " +
        "FROM Person " +
        "WHERE Name= @Name"

      val resultSet = db.singleUse.executeQuery(
        Statement.newBuilder(sql).bind("Name").to(name).build()
      )

      (resultSet, rotxn)
    }.bracket {
      case (resultSet, rotxn) =>
        IO {
          val result =
            scala.collection.mutable.Map.empty[String, Person]

          while (resultSet.next()) {
            result += (resultSet.getString(0) -> new Person(resultSet.getString(0)))
          }

          (result.toMap, rotxn.getReadTimestamp)
        }
    } {
      case (resultSet, _) =>
        IO(resultSet.close())
    }
 }
```
Any help would be welcomed. :) 
Regards..

Edit: 
I tried closing resultSet and/or rotxn with resultSet.close() and rotxn.close() and then calling rotxn.getReadTimestamp(), but didn't have much luck. I got the same error message.

Edit2:
It might be worth mentioning that I am using Spanner Java lib: com.google.cloud:google-cloud-spanner:2.0.1
Also, I am using Spanner emulator, as I am doing this locally for now.

**Comment by olavloite** [comment]
This problem turned out to be caused by the following line:

```scala
      val resultSet = db.singleUse.executeQuery(
        Statement.newBuilder(sql).bind("Name").to(name).build()
      )
```

The query is not using the read-only transaction, but starts a separate single-use read-only transaction. The read-only transaction has therefore not yet been used when the call to `getReadTimestamp()` is executed.

The query should have been:

```scala
      val resultSet = rotxn.executeQuery(
        Statement.newBuilder(sql).bind("Name").to(name).build()
      )
```

Source:
https://stackoverflow.com/questions/66641889/cloud-spanner-db-unable-to-read-timestamp-from-readonlytransaction-getreadtime
